properties:
  configurationVersion: 0.2.0
  resources:
    - id: 「ホーム」メニューを非表示に
      resource: PSDscResources/Registry
      settings:
        Key: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{f874310e-b6b7-47dc-bc84-b9e6b38f5903}
        ValueName: ""
        Force: true
    
    - id: 「ギャラリー」メニューを非表示に
      resource: PSDscResources/Registry
      settings:
        Key: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{e88865ea-0e1c-4e20-9aa6-edcd0212c87c}
        ValueName: ""
        Force: true

    - id: 隠しファイルを表示
      resource: PSDscResources/Registry
      settings:
        Key: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        ValueName: Hidden
        ValueType: Dword
        ValueData: 1
        Force: true
    
    - id: 拡張子を表示
      resource: PSDscResources/Registry
      settings:
        Key: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        ValueName: HideFileExt
        ValueType: Dword
        ValueData: 0
        Force: true
    
    - id: タスクバーの検索ボックスを非表示に
      resource: PSDscResources/Registry
      settings:
        Key: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search
        ValueName: SearchboxTaskbarMode
        ValueType: Dword
        ValueData: 0
        Force: true

    - id: タスクバーの「タスクビュー」アイコンを非表示に
      resource: PSDscResources/Registry
      settings:
        Key: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        ValueName: ShowTaskViewButton
        ValueType: Dword
        ValueData: 0
        Force: true

    - id: タスクバーのウィジェットを非表示に
      resource: PSDscResources/Registry
      settings:
        Key: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        ValueName: TaskbarDa
        ValueType: Dword
        ValueData: 0
        Force: true

    - id: 1Passwordのインストール
      resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: AgileBits.1Password
        source: winget

    - id: Google Chromeのインストール
      resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Google.Chrome
        source: winget

    - id: Google日本語入力のインストール
      resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Google.JapaneseIME
        source: winget

    - id: VSCodeのインストール
      resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Microsoft.VisualStudioCode
        source: winget

    - id: Visual Studio 2022 Communityのインストール
      resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Microsoft.VisualStudio.2022.Community
        source: winget

    - id: PowerToysのインストール
      resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Microsoft.PowerToys
        source: winget

    - id: JetBrains Toolboxのインストール
      resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: JetBrains.Toolbox
        source: winget

    - id: Steamのインストール
      resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Valve.Steam
        source: winget

    - id: Epic Games Launcherのインストール
      resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: EpicGames.EpicGamesLauncher
        source: winget

    # https://learn.microsoft.com/ja-jp/windows/powertoys/dsc-configure 
    - id: PowerToysの設定
      resource: Microsoft.PowerToys.Configure/PowerToysConfigure
      dependsOn:
        - PowerToysのインストール
      settings:
        AlwaysOnTop:
          Enabled: false
        Awake:
          Enabled: false
        ColorPicker:
          Enabled: false
        CropAndLock:
          Enabled: false
        EnvironmentVariables:
          Enabled: false
        FancyZones:
          Enabled: false
        FileLocksmith:
          Enabled: false
        FindMyMouse:
          Enabled: false
        Hosts:
          Enabled: false
        ImageResizer:
          Enabled: false
        KeyboardManager:
          Enabled: true
        MeasureTool:
          Enabled: false
        MouseHighlighter:
          Enabled: false
        MouseJump:
          Enabled: false
        MousePointerCrosshairs:
          Enabled: false
        MouseWithoutBorders:
          Enabled: false
        Peek:
          Enabled: false
        PowerAccent:
          Enabled: false
        PowerLauncher:
          Enabled: false



